//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerCalibration.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("COM1")]
        public string Meter_COM_Port_Name {
            get {
                return ((string)(this["Meter_COM_Port_Name"]));
            }
            set {
                this["Meter_COM_Port_Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files (x86)\\Ember\\ISA3 Utilities\\bin")]
        public string Ember_BinPath {
            get {
                return ((string)(this["Ember_BinPath"]));
            }
            set {
                this["Ember_BinPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("FT232H")]
        public string Relay_Controller_Type {
            get {
                return ((string)(this["Relay_Controller_Type"]));
            }
            set {
                this["Relay_Controller_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Last_Used_Board {
            get {
                return ((string)(this["Last_Used_Board"]));
            }
            set {
                this["Last_Used_Board"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Meter_Manual_Measurement {
            get {
                return ((bool)(this["Meter_Manual_Measurement"]));
            }
            set {
                this["Meter_Manual_Measurement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IP")]
        public string Ember_Interface {
            get {
                return ((string)(this["Ember_Interface"]));
            }
            set {
                this["Ember_Interface"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("172.19.14.121")]
        public string Ember_Interface_IP_Address {
            get {
                return ((string)(this["Ember_Interface_IP_Address"]));
            }
            set {
                this["Ember_Interface_IP_Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Ember_Interface_USB_Address {
            get {
                return ((string)(this["Ember_Interface_USB_Address"]));
            }
            set {
                this["Ember_Interface_USB_Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("All")]
        public string Shortcut_Spacebar_Action {
            get {
                return ((string)(this["Shortcut_Spacebar_Action"]));
            }
            set {
                this["Shortcut_Spacebar_Action"] = value;
            }
        }
    }
}
